### ISSUE TITLE
Explanation of the hack.

### ISSUE THREAD

**Issue by santiagopuentep** [benlavalley/lightspeed#1]
Hi @benlavalley.

I found this hack reading this issue you posted: https://github.com/meteor/meteor/issues/9660

Would you mind explaining this hack a little more? Is it to stop the main js payload from blocking the first render right?

Thanks!

**Comment by benlavalley** [comment]
@santiagopuentep Just saw this! Yes, that is pretty much what it does. I haven't refactored this to work with the Meteor connection handler changes in 1.6 as it really is just a "synthetic" change to how fast the browser thinks it is rendering the page. I might implement it again if I feel like having crawlers think my site is loading in < 150ms instead of 500-1000ms as it does now.
